default_install_hook_types:
- pre-commit
- post-checkout
- post-merge
- post-rewrite
repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.9
  hooks:
  - id: uv-lock
    name: update uv.lock
  - id: uv-sync
    name: update local dependencies
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.8
  hooks:
  - id: ruff
    name: ruff linting + fixing
    args: [ --fix ]
  - id: ruff-format
    name: ruff formatting
- repo: https://github.com/facebook/pyrefly
  rev: 0.28.1
  hooks:
    - id: pyrefly-typecheck
- repo: local
  hooks:
    - id: pytest-check
      name: run Python tests
      language: system
      entry: ./.venv/bin/pytest
      types: [python]
      pass_filenames: false
      always_run: true